Use const generics instead of typenum.
bodil/sized-chunks pull request #25
Opened 2021-04-26 13:04 UTC by bodil

With const generics support in `bitmaps` finally sorted, I think this is ready to merge, but I'm putting it here in a PR for now because I don't want to put this in master until `im` is ready for it, being a huge breaking change and all. Eyes on it would still be appreciated.

2021-04-26 13:16 UTC, bodil commented
Granted, this is the least exciting PR ever as it changes no actual code, only every type in the API, in more or less exactly the same way.

2021-04-27 20:11 UTC, kornelski approved these changes

2021-04-28 12:53 UTC, kornelski commented
Can you update fuzz tests? They're currently failing to compile:

```

error[E0107]: this struct takes 2 generic arguments but only 1 generic argument was supplied
  --> fuzz_targets/ring_buffer.rs:24:14
   |
24 |     FromIter(RingBuffer<A>),
   |              ^^^^^^^^^^ - supplied 1 generic argument
   |              |
   |              expected 2 generic arguments
```

2021-04-28 12:53 UTC, kornelski requested changes
.

2021-05-21 20:56 UTC, kornelski approved these changes

2021-05-21 20:58 UTC, merged